[workspace]
members = [
    "smartpack",
    "kernel",
    "tools/image_builder",
    "tools/js_harness",
    "smartsdk",
    "tools/module_loader",
    "apps/dashboard",
    "apps/shell",
    "apps/browser",
    "apps/pkg_installer",
    "apps/games",
    "apps/office",
    "apps/spreadsheet",
    "apps/presentation",
    "apps/crm",
    "apps/image_viewer",
    "apps/pdf_reader",
    "apps/video_player",
    "apps/email_client",
    "drivers/test_driver",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Arvind Kumar Singh <arvind1420@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 2
lto = true
