[workspace]
members = [
    "smartpack",
    "kernel",
    "tools/image_builder",
    "smartsdk",
    "tools/module_loader",
    "apps/dashboard",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Smart OS Contributors"]
license = "MIT"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 2
lto = true
